### ISSUE TITLE
老哥，vue2引入了 ”@vue/composition-api”， 还是会报错

### ISSUE THREAD

**Issue by io-o** [backrunner/vue-share-popup#1]
![image](https://user-images.githubusercontent.com/22197685/133744057-1a7bec30-3bfc-44f5-b94a-cae2f0c21f11.png)

在线demo: https://codesandbox.io/s/nostalgic-sun-m2ube?file=/src/App.vue

**Comment by backrunner** [comment]
这个库用了`vue-demi`同时兼容vue 2和3，它靠postInstall脚本在安装的时候检测环境，如果检测失败会自动引vue 3。在CodeSandbox里这个检测会有问题的，建议本地起一个demo试试。

**Comment by backrunner** [comment]
多日没有回复，我先close了，有问题欢迎再开

**Comment by io-o** [comment]
不好意思， 最近没测试，本地起demo，确实可以， 谢谢
